{% set name = "libdlf" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3523aaa20d4f692a2f44794bae609762dd3e5f28a84ec8f7d09c77daa94044a0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - libdlf

about:
  home: https://github.com/emsig/libdlf
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  summary: Library for Digital Linear Filters (DLF)
  description: |
    Library for Digital Linear Filters (DLF) as used, for instance,
    in Geophysics for electromagnetic modelling.
  doc_url: https://github.com/emsig/libdlf
  dev_url: https://github.com/emsig/libdlf

extra:
  recipe-maintainers:
    - prisae
